export const countries = {
  list: [
    {name: 'Afganistán', code: 'AF'},
    {name: 'Islas de Aland', code: 'AX'},
    {name: 'Albania', code: 'AL'},
    {name: 'Argelia', code: 'DZ'},
    {name: 'Samoa Americana', code: 'AS'},
    {name: 'Andorra', code: 'AD'},
    {name: 'Angola', code: 'AO'},
    {name: 'Anguila', code: 'AI'},
    {name: 'Antártida', code: 'AQ'},
    {name: 'Antigua y Barbuda', code: 'AG'},
    {name: 'Argentina', code: 'AR'},
    {name: 'Armenia', code: 'AM'},
    {name: 'Aruba', code: 'AW'},
    {name: 'Australia', code: 'AU'},
    {name: 'Austria', code: 'AT'},
    {name: 'Azerbaiyán', code: 'AZ'},
    {name: 'Bahamas', code: 'BS'},
    {name: 'Baréin', code: 'BH'},
    {name: 'Bangladesh', code: 'BD'},
    {name: 'Barbados', code: 'BB'},
    {name: 'Bielorrusia', code: 'BY'},
    {name: 'Bélgica', code: 'BE'},
    {name: 'Belice', code: 'BZ'},
    {name: 'Benín', code: 'BJ'},
    {name: 'Bermuda', code: 'BM'},
    {name: 'Bután', code: 'BT'},
    {name: 'Bolivia', code: 'BO'},
    {name: 'Bonaire, San Eustaquio y Saba', code: 'BQ'},
    {name: 'Bosnia y Herzegovina', code: 'BA'},
    {name: 'Botsuana', code: 'BW'},
    {name: 'Isla Bouvet', code: 'BV'},
    {name: 'Brasil', code: 'BR'},
    {name: 'Territorio Británico del Océano Índico', code: 'IO'},
    {name: 'Islas Vírgenes Británicas', code: 'VG'},
    {name: 'Brunei', code: 'BN'},
    {name: 'Bulgaria', code: 'BG'},
    {name: 'Burkina Faso', code: 'BF'},
    {name: 'Burundi', code: 'BI'},
    {name: 'Camboya', code: 'KH'},
    {name: 'Camerún', code: 'CM'},
    {name: 'Canadá', code: 'CA'},
    {name: 'Cabo Verde', code: 'CV'},
    {name: 'Islas Caimán', code: 'KY'},
    {name: 'República de África Central', code: 'CF'},
    {name: 'Chad', code: 'TD'},
    {name: 'Chile', code: 'CL'},
    {name: 'China', code: 'CN'},
    {name: 'Isla de Pascua', code: 'CX'},
    {name: 'Islas Cocos', code: 'CC'},
    {name: 'Colombia', code: 'CO'},
    {name: 'Comoras', code: 'KM'},
    {name: 'Islas Cook', code: 'CK'},
    {name: 'Costa Rica', code: 'CR'},
    {name: 'Croacia', code: 'HR'},
    {name: 'Cuba', code: 'CU'},
    {name: 'Curazao', code: 'CW'},
    {name: 'Chipre', code: 'CY'},
    {name: 'República Checa', code: 'CZ'},
    {name: 'República Democrática del Congo', code: 'CD'},
    {name: 'Dinamarca', code: 'DK'},
    {name: 'Yibuti', code: 'DJ'},
    {name: 'Dominica', code: 'DM'},
    {name: 'República Dominicana', code: 'DO'},
    {name: 'Timor Oriental', code: 'TL'},
    {name: 'Ecuador', code: 'EC'},
    {name: 'Egipto', code: 'EG'},
    {name: 'El Salvador', code: 'SV'},
    {name: 'Guinea Ecuatorial', code: 'GQ'},
    {name: 'Eritrea', code: 'ER'},
    {name: 'Estonia', code: 'EE'},
    {name: 'Etiopía', code: 'ET'},
    {name: 'Islas Malvinas', code: 'FK'},
    {name: 'Islas Faroe', code: 'FO'},
    {name: 'Fiji', code: 'FJ'},
    {name: 'Finlandia', code: 'FI'},
    {name: 'Francia', code: 'FR'},
    {name: 'Guayana Francesa', code: 'GF'},
    {name: 'Polinesia Francesa', code: 'PF'},
    {name: 'Territorios del sur Franceses', code: 'TF'},
    {name: 'Gabón', code: 'GA'},
    {name: 'Gambia', code: 'GM'},
    {name: 'Georgia', code: 'GE'},
    {name: 'Alemania', code: 'DE'},
    {name: 'Ghana', code: 'GH'},
    {name: 'Gibraltar', code: 'GI'},
    {name: 'Grecia', code: 'GR'},
    {name: 'Groenlandia', code: 'GL'},
    {name: 'Granada', code: 'GD'},
    {name: 'Guadalupe', code: 'GP'},
    {name: 'Guam', code: 'GU'},
    {name: 'Guatemala', code: 'GT'},
    {name: 'Guernsey', code: 'GG'},
    {name: 'Guinea', code: 'GN'},
    {name: 'Guinea Bissau', code: 'GW'},
    {name: 'Guyana', code: 'GY'},
    {name: 'Haití', code: 'HT'},
    {name: 'Islas Heard y McDonald', code: 'HM'},
    {name: 'Honduras', code: 'HN'},
    {name: 'Hong Kong', code: 'HK'},
    {name: 'Hungría', code: 'HU'},
    {name: 'Islandia', code: 'IS'},
    {name: 'India', code: 'IN'},
    {name: 'Indonesia', code: 'ID'},
    {name: 'Irán', code: 'IR'},
    {name: 'Irak', code: 'IQ'},
    {name: 'Irlanda', code: 'IE'},
    {name: 'Isla de Man', code: 'IM'},
    {name: 'Israel', code: 'IL'},
    {name: 'Italia', code: 'IT'},
    {name: 'Costa de Marfil', code: 'CI'},
    {name: 'Jamaica', code: 'JM'},
    {name: 'Japón', code: 'JP'},
    {name: 'Jersey', code: 'JE'},
    {name: 'Jordania', code: 'JO'},
    {name: 'Kazajistán', code: 'KZ'},
    {name: 'Kenia', code: 'KE'},
    {name: 'Kiribati', code: 'KI'},
    {name: 'Kosovo', code: 'XK'},
    {name: 'Kuwait', code: 'KW'},
    {name: 'Kirguistán', code: 'KG'},
    {name: 'Laos', code: 'LA'},
    {name: 'Letonia', code: 'LV'},
    {name: 'Líbano', code: 'LB'},
    {name: 'Lesoto', code: 'LS'},
    {name: 'Liberia', code: 'LR'},
    {name: 'Libia', code: 'LY'},
    {name: 'Liechtenstein', code: 'LI'},
    {name: 'Lituania', code: 'LT'},
    {name: 'Luxemburgo', code: 'LU'},
    {name: 'Macao', code: 'MO'},
    {name: 'Macedonia', code: 'MK'},
    {name: 'Madagascar', code: 'MG'},
    {name: 'Malaui', code: 'MW'},
    {name: 'Malasia', code: 'MY'},
    {name: 'Maldivas', code: 'MV'},
    {name: 'Malí', code: 'ML'},
    {name: 'Malta', code: 'MT'},
    {name: 'Islas Marshall', code: 'MH'},
    {name: 'Martinica', code: 'MQ'},
    {name: 'Mauritania', code: 'MR'},
    {name: 'Mauricio', code: 'MU'},
    {name: 'Mayotte', code: 'YT'},
    {name: 'México', code: 'MX'},
    {name: 'Micronesia', code: 'FM'},
    {name: 'Moldavia', code: 'MD'},
    {name: 'Mónaco', code: 'MC'},
    {name: 'Mongolia', code: 'MN'},
    {name: 'Montenegro', code: 'ME'},
    {name: 'Montserrat', code: 'MS'},
    {name: 'Marruecos', code: 'MA'},
    {name: 'Mozambique', code: 'MZ'},
    {name: 'Myanmar', code: 'MM'},
    {name: 'Namibia', code: 'NA'},
    {name: 'Nauru', code: 'NR'},
    {name: 'Nepal', code: 'NP'},
    {name: 'Países Bajos', code: 'NL'},
    {name: 'Antillas Holandesas', code: 'AN'},
    {name: 'Nueva Caledonia', code: 'NC'},
    {name: 'Nueva Zelanda', code: 'NZ'},
    {name: 'Nicaragua', code: 'NI'},
    {name: 'Níger', code: 'NE'},
    {name: 'Nigeria', code: 'NG'},
    {name: 'Niue', code: 'NU'},
    {name: 'Isla Norfolk', code: 'NF'},
    {name: 'Corea del Norte', code: 'KP'},
    {name: 'Islas Marianas del Norte', code: 'MP'},
    {name: 'Noruega', code: 'NO'},
    {name: 'Omán', code: 'OM'},
    {name: 'Pakistán', code: 'PK'},
    {name: 'Palaos', code: 'PW'},
    {name: 'Territorios Palestinos', code: 'PS'},
    {name: 'Panamá', code: 'PA'},
    {name: 'Papúa Nueva Guinea', code: 'PG'},
    {name: 'Paraguay', code: 'PY'},
    {name: 'Perú', code: 'PE'},
    {name: 'Filipinas', code: 'PH'},
    {name: 'Islas Pitcairn', code: 'PN'},
    {name: 'Polonia', code: 'PL'},
    {name: 'Portugal', code: 'PT'},
    {name: 'Puerto Rico', code: 'PR'},
    {name: 'Catar', code: 'QA'},
    {name: 'República del Congo', code: 'CG'},
    {name: 'Reunión', code: 'RE'},
    {name: 'Rumanía', code: 'RO'},
    {name: 'Rusia', code: 'RU'},
    {name: 'Ruanda', code: 'RW'},
    {name: 'San Bartolomé', code: 'BL'},
    {name: 'Santa Elena', code: 'SH'},
    {name: 'San Cristóbal y Nieves', code: 'KN'},
    {name: 'Santa Lucía', code: 'LC'},
    {name: 'San Martín', code: 'MF'},
    {name: 'San Pedro y Miguelón', code: 'PM'},
    {name: 'San Vicente y las Granadinas', code: 'VC'},
    {name: 'Samoa Occidental', code: 'WS'},
    {name: 'San Marino', code: 'SM'},
    {name: 'Santo Tomé y Príncipe', code: 'ST'},
    {name: 'Arabia Saudita', code: 'SA'},
    {name: 'Senegal', code: 'SN'},
    {name: 'Serbia', code: 'RS'},
    {name: 'Serbia y Montenegro', code: 'CS'},
    {name: 'Seychelles', code: 'SC'},
    {name: 'Sierra Leona', code: 'SL'},
    {name: 'Singapur', code: 'SG'},
    {name: 'San Martín', code: 'SX'},
    {name: 'Eslovaquia', code: 'SK'},
    {name: 'Eslovenia', code: 'SI'},
    {name: 'Islas Salomón', code: 'SB'},
    {name: 'Somalia', code: 'SO'},
    {name: 'Sudáfrica', code: 'ZA'},
    {name: 'Islas Georgia del Sur y Sandwich del Sur', code: 'GS'},
    {name: 'Corea del Sur', code: 'KR'},
    {name: 'Sudán del Sur', code: 'SS'},
    {name: 'España', code: 'ES'},
    {name: 'Sri Lanka', code: 'LK'},
    {name: 'Sudán', code: 'SD'},
    {name: 'Surinam', code: 'SR'},
    {name: 'Islas Svalbard y Jan Mayen', code: 'SJ'},
    {name: 'Suazilandia', code: 'SZ'},
    {name: 'Suecia', code: 'SE'},
    {name: 'Suiza', code: 'CH'},
    {name: 'Siria', code: 'SY'},
    {name: 'Taiwán', code: 'TW'},
    {name: 'Tayikistán', code: 'TJ'},
    {name: 'Tanzania', code: 'TZ'},
    {name: 'Tailandia', code: 'TH'},
    {name: 'República Togolesa', code: 'TG'},
    {name: 'Islas Tokelau', code: 'TK'},
    {name: 'Tonga', code: 'TO'},
    {name: 'Trinidad y Tobago', code: 'TT'},
    {name: 'Túnez', code: 'TN'},
    {name: 'Turquía', code: 'TR'},
    {name: 'Turkmenistán', code: 'TM'},
    {name: 'Islas Turcos y Caicos', code: 'TC'},
    {name: 'Tuvalu', code: 'TV'},
    {name: 'Islas Vírgenes de los EE.UU.', code: 'VI'},
    {name: 'Uganda', code: 'UG'},
    {name: 'Ucrania', code: 'UA'},
    {name: 'Emiratos Árabes Unidos', code: 'AE'},
    {name: 'Reino Unido', code: 'GB'},
    {name: 'Estados Unidos (USA)', code: 'US'},
    {name: 'Islas menores alejadas de los Estados Unidos', code: 'UM'},
    {name: 'Uruguay', code: 'UY'},
    {name: 'Uzbekistán', code: 'UZ'},
    {name: 'Vanuatu', code: 'VU'},
    {name: 'Vaticano', code: 'VA'},
    {name: 'Venezuela', code: 'VE'},
    {name: 'Vietnam', code: 'VN'},
    {name: 'Wallis y Futuna', code: 'WF'},
    {name: 'Sahara Occidental', code: 'EH'},
    {name: 'Yemen', code: 'YE'},
    {name: 'Zambia', code: 'ZM'},
    {name: 'Zimbabue', code: 'ZW'}

  ]

};
